#ifndef PLSTATE_H
#define PLSTATE_H

enum PLConnectionState {
  PL_STATE_BOOTING,
  PL_STATE_WIFI_CONNECTING,
  PL_STATE_LOCAL_CONNECTING,
  PL_STATE_LOCAL_CONNECTED,
  PL_STATE_CLOUD_CONNECTING,
  PL_STATE_CLOUD_CONNECTED,
  PL_STATE_RECONNECTING,
  PL_STATE_OFFLINE_IDLE,
  PL_STATE_ERROR
};

const char* plStateToString(PLConnectionState state);

#endif
